# These are supported funding model platforms

github: [vxst]

I'm currently in Switzerland, seeking refugee status.
As I navigate this process, I'm prohibited from
undertaking any form of paid work. My health condition
brings many unexpected expenses, which leads me to seek
temporary support. I intend to view any sponsorship as
a loan. Once I'm permitted to work, finding employment
will be my utmost priority, and repaying this sponsorship
will be at the forefront of my financial obligations.
Furthermore, I commit to paying back these funds at an
annual interest rate of 7%. I humbly appeal to your humanity,
understanding the profound impact your help would make in
my current situation. Thank you for considering my plight.
